# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bindex/all/bindex.rbi
#
# bindex-0.7.0
module Skiptrace
  def self.current_bindings; end
end
class Exception
  def bindings; end
end
