# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/datetime_picker_rails/all/datetime_picker_rails.rbi
#
# datetime_picker_rails-0.0.7
module DateTimePicker
end
module DateTimePicker::Rails
end
class DateTimePicker::Rails::Engine < Rails::Engine
end
