# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/font-awesome-rails/all/font-awesome-rails.rbi
#
# font-awesome-rails-4.7.0.5
module FontAwesome
end
module FontAwesome::Rails
end
class FontAwesome::Rails::Engine < Rails::Engine
end
