# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/image_size/all/image_size.rbi
#
# image_size-1.5.0
class ImageSize
  def detect_format(ir); end
  def detect_png_type(ir); end
  def format; end
  def h; end
  def height; end
  def initialize(data); end
  def self.dpi; end
  def self.dpi=(dpi); end
  def self.path(path); end
  def size; end
  def size_of_apng(ir); end
  def size_of_bmp(ir); end
  def size_of_cur(ir); end
  def size_of_gif(ir); end
  def size_of_ico(ir); end
  def size_of_jpeg(ir); end
  def size_of_mng(ir); end
  def size_of_pcx(ir); end
  def size_of_png(ir); end
  def size_of_ppm(ir); end
  def size_of_psd(ir); end
  def size_of_svg(ir); end
  def size_of_swf(ir); end
  def size_of_tiff(ir); end
  def size_of_webp(ir); end
  def size_of_xbm(ir); end
  def size_of_xpm(ir); end
  def w; end
  def width; end
end
class ImageSize::FormatError < StandardError
end
class ImageSize::Size < Array
  def to_s; end
end
class ImageSize::ImageReader
  def [](offset, length); end
  def close; end
  def data; end
  def initialize(data_or_io); end
end
