# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/image_info/all/image_info.rbi
#
# image_info-1.1.2
module ImageInfo
  def self.from(urls, options = nil); end
  extend ImageInfo::Configurable
end
class ImageInfo::Image
  def height; end
  def height=(arg0); end
  def initialize(uri); end
  def size; end
  def type; end
  def type=(arg0); end
  def uri; end
  def valid?; end
  def width; end
  def width=(arg0); end
end
class ImageInfo::Image::NullUri
  def host; end
end
class ImageInfo::Parser
  def call; end
  def data; end
  def image; end
  def initialize(image, data); end
  def parser; end
  def set_image_size; end
  def set_image_type; end
end
class ImageInfo::NullParser
  def format; end
  def height; end
  def width; end
end
class ImageInfo::RequestHandler
  def buffer; end
  def build; end
  def found_image_info?(chunk); end
  def image; end
  def initialize(image); end
end
class ImageInfo::Processor
  def hydra; end
  def images; end
  def initialize(urls, options = nil); end
  def options; end
  def process; end
end
class ImageInfo::Configuration
  def initialize; end
  def max_concurrency; end
  def max_concurrency=(arg0); end
end
module ImageInfo::Configurable
  def config; end
  def configure; end
end
