# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kgio/all/kgio.rbi
#
# kgio-2.11.2
module Kgio::SocketMethods
  def kgio_addr!; end
  def kgio_addr; end
  def kgio_addr=(arg0); end
  def kgio_autopush=(arg0); end
  def kgio_autopush?; end
  def kgio_peek(*arg0); end
  def kgio_read!(*arg0); end
  def kgio_read(*arg0); end
  def kgio_syssend(arg0, arg1); end
  def kgio_trypeek(*arg0); end
  def kgio_tryread(*arg0); end
  def kgio_trywrite(arg0); end
  def kgio_trywritev(arg0); end
  def kgio_write(arg0); end
  def kgio_writev(arg0); end
end
module Kgio::DefaultWaiters
  def kgio_wait_readable(*arg0); end
  def kgio_wait_writable(*arg0); end
end
module Kgio
  def self.accept_class; end
  def self.accept_class=(arg0); end
  def self.accept_cloexec=(arg0); end
  def self.accept_cloexec?; end
  def self.accept_nonblock=(arg0); end
  def self.accept_nonblock?; end
  def self.autopush=(arg0); end
  def self.autopush?; end
  def self.poll(*arg0); end
  def self.trypeek(*arg0); end
  def self.tryread(*arg0); end
  def self.trywrite(arg0, arg1); end
  def self.trywritev(arg0, arg1); end
end
module Kgio::PipeMethods
  def kgio_read!(*arg0); end
  def kgio_read(*arg0); end
  def kgio_tryread(*arg0); end
  def kgio_trywrite(arg0); end
  def kgio_trywritev(arg0); end
  def kgio_write(arg0); end
  def kgio_writev(arg0); end
end
class Kgio::Socket < Socket
  def self.connect(arg0); end
  def self.new(*arg0); end
  def self.start(arg0); end
end
class Kgio::TCPSocket < TCPSocket
  def self.new(arg0, arg1); end
  def self.start(arg0, arg1); end
end
class Kgio::UNIXSocket < UNIXSocket
  def self.new(arg0); end
  def self.start(arg0); end
end
class Kgio::UNIXServer < UNIXServer
  def kgio_accept(*arg0); end
  def kgio_tryaccept(*arg0); end
end
class Kgio::TCPServer < TCPServer
  def kgio_accept(*arg0); end
  def kgio_tryaccept(*arg0); end
end
class Kgio::File < File
  def self.tryopen(*arg0); end
end
class Kgio::Pipe < IO
  def self.new(*arg0); end
  include Kgio::PipeMethods
end
