# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/net_http_timeout_errors/all/net_http_timeout_errors.rbi
#
# net_http_timeout_errors-0.3.0
class NetHttpTimeoutErrors
  def self.all; end
  def self.conflate; end
end
class NetHttpTimeoutError < StandardError
  def initialize(original_error); end
  def original_error; end
end
