# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth-twitter/all/omniauth-twitter.rbi
#
# omniauth-twitter-1.4.0
module OmniAuth
end
module OmniAuth::Twitter
end
module OmniAuth::Strategies
end
class OmniAuth::Strategies::Twitter < OmniAuth::Strategies::OAuth
  def callback_path; end
  def callback_url; end
  def image_url; end
  def old_callback_url; end
  def old_request_phase; end
  def raw_info; end
  def request_phase; end
end
