# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth-github/all/omniauth-github.rbi
#
# omniauth-github-1.3.0
module OmniAuth
end
module OmniAuth::GitHub
end
module OmniAuth::Strategies
end
class OmniAuth::Strategies::GitHub < OmniAuth::Strategies::OAuth2
  def authorize_params; end
  def callback_url; end
  def email; end
  def email_access_allowed?; end
  def emails; end
  def primary_email; end
  def raw_info; end
  def request_phase; end
  extend OmniAuth::Strategy::ClassMethods
end
