# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/partially_useful/all/partially_useful.rbi
#
# partially_useful-6.0.0
module PartiallyUseful
end
module PartiallyUseful::PartialRenderer
  def html_context?(context); end
  def render_partial(context, options, &block); end
end
class PartiallyUseful::Railtie < Rails::Railtie
end
