# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-cache/all/rack-cache.rbi
#
# rack-cache-1.9.0
module Rack::Cache
  def self.new(backend, options = nil, &b); end
end
