# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_stdout_logging/all/rails_stdout_logging.rbi
#
# rails_stdout_logging-0.0.5
module RailsStdoutLogging
end
class RailsStdoutLogging::StdoutLogger < ActiveSupport::Logger
  include ActiveSupport::LoggerSilence
  include LoggerSilence
end
class RailsStdoutLogging::Rails
  def self.heroku_stdout_logger; end
  def self.log_level; end
  def self.set_logger; end
end
class RailsStdoutLogging::Rails3 < RailsStdoutLogging::Rails
  def self.set_logger(config); end
end
class RailsStdoutLogging::Railtie < Rails::Railtie
end
