# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rails_serve_static_assets/all/rails_serve_static_assets.rbi
#
# rails_serve_static_assets-0.0.5
module RailsServeStaticAssets
end
class RailsServeStaticAssets::Railtie < Rails::Railtie
end
