# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-ll/all/ruby-ll.rbi
#
# ruby-ll-2.1.2
module LL
end
class LL::Driver
  def id_to_terminal(id); end
  def id_to_type(id); end
  def parse; end
  def parser_error(stack_type, stack_value, token_type, token_value); end
  def parser_error_message(stack_type, stack_value, token_type); end
end
class LL::DriverConfig
  def actions; end
  def actions=(array); end
  def actions_native=(arg0); end
  def rules; end
  def rules=(array); end
  def rules_native=(arg0); end
  def table; end
  def table=(array); end
  def table_native=(arg0); end
  def terminals; end
  def terminals=(array); end
  def terminals_native=(arg0); end
end
class LL::ParserError < StandardError
end
class LL::ConfigurationCompiler
  def generate(grammar); end
  def generate_action_bodies(grammar); end
  def generate_actions(grammar); end
  def generate_name(grammar); end
  def generate_namespace(grammar); end
  def generate_rules(grammar); end
  def generate_table(grammar); end
  def generate_terminals(grammar); end
end
