# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/selectize-rails/all/selectize-rails.rbi
#
# selectize-rails-0.12.6
module Selectize
end
module Selectize::Rails
end
class Selectize::Rails::Engine < Rails::Engine
end
