# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/slim-rails/all/slim-rails.rbi
#
# slim-rails-3.2.0
module Slim
end
module Slim::Rails
end
module Slim::Rails::RegisterEngine
  def self._register_engine(config); end
  def self._register_engine3(app); end
  def self.register_engine(app, config); end
end
class Slim::Rails::RegisterEngine::Transformer
  def self.call(input); end
end
class Slim::Rails::Railtie < Rails::Railtie
end
