# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/validate_url/all/validate_url.rbi
#
# validate_url-1.0.8
module ActiveModel
end
module ActiveModel::Validations
end
class ActiveModel::Validations::UrlValidator < ActiveModel::EachValidator
  def filtered_options(value); end
  def initialize(options); end
  def validate_each(record, attribute, value); end
end
module ActiveModel::Validations::ClassMethods
  def validates_url(*attr_names); end
end
