# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/whitelabel/all/whitelabel.rbi
#
# whitelabel-0.3.0
module Whitelabel
  def self.[](accessor); end
  def self.each_label(&block); end
  def self.find_label(pattern, identifier = nil); end
  def self.from_file(path); end
  def self.label; end
  def self.label=(label); end
  def self.label_for(pattern, identifier = nil); end
  def self.labels; end
  def self.labels=(arg0); end
  def self.reset!; end
  def self.with_label(tmp = nil); end
end
