FROM ruby:2.2.1

EXPOSE 5000
ENV APP_DIR=/opt/on_ruby/
WORKDIR $APP_DIR

RUN apt-get update
RUN apt-get install nodejs -y

COPY Gemfile* .ruby-version $APP_DIR

RUN bundle install --jobs 4
CMD script/server
