source 'http://rubygems.org'
ruby '~> 2.3.0'

gem 'puma',                   '~> 3.6'
gem 'rails',                  '~> 4.2.7'
gem 'responders',             '~> 2.0'
gem 'rails-observers',        '~> 0.1.2'
gem 'pg',                     '~> 0.17.1'
gem 'rack-cache',             '~> 1.2'
gem 'slim-rails',             '~> 3.0'
gem 'redcarpet',              '~> 3.0'
gem 'friendly_id',            '~> 5.1.0'
gem 'omniauth',               '~> 1.6.0'
gem 'omniauth-twitter',       '~> 1.3.0'
gem 'omniauth-github',        '~> 1.2.3'
gem 'ri_cal',                 '~> 0.8.8'
gem 'decent_exposure',        '~> 2.3.1'
gem 'geocoder',               '~> 1.1'
gem 'acts_as_api',            '~> 0.4.2'
gem 'whitelabel',             '~> 0.3'
gem 'exception_notification', '~> 4.0.1'
gem 'feedjira',               '~> 1.2'
gem 'formtastic',             '~> 3.1.5'
gem 'kaminari',               '~> 0.15.0'
gem 'typus',                  github: 'typus/typus'
gem 'jquery-rails',           '~> 3.0'
gem 'sass-rails',             '~> 5.0.1'
gem 'compass-rails',          '~> 2.0.4'
gem 'coffee-rails',           '~> 4.0.1'
gem 'font-awesome-rails',     '~> 4.0'
gem 'uglifier',               '~> 3.1'
gem 'one_signal',             '~> 0.0.10'
gem 'link_thumbnailer',       '~> 2.4.0'

group :production do
  gem 'dalli',            '~> 2.7.0'
  gem 'kgio',             '~> 2.9.2'
  gem 'lograge',          '~> 0.3.0'
  gem 'heroku-deflater',  '~> 0.5.3'
  gem 'rails_12factor',   '~> 0.0.2'
end

group :development do
  gem 'partially_useful'
end

group :development, :test do
  gem 'letter_opener'
  gem 'faker'
  gem 'byebug'
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'factory_girl_rails'
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
end
