#! /bin/sh
set -e

if [[ `psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='onruby_test'"` == "1" ]]
then
    echo "Database already exists"
else
    psql -U postgres -tAc 'create database onruby_test;'
fi


RAILS_ENV=test bundle exec rake db:test:prepare
